(function(global){
function definePlugin(name, fn){ if(global.Seriously && Seriously.plugin){ Seriously.plugin(name, fn); } }
definePlugin('bleachbypass', function(options){ var self=this; self.inputs={source:null}; self.outputs={output:null}; self.params={amount:1}; self.process=function(){ if(!self.inputs.source||!self.outputs.output) return; var ctx=self.outputs.output.getContext('2d'); var w=self.outputs.output.width; var h=self.outputs.output.height; ctx.drawImage(self.inputs.source,0,0,w,h); var img=ctx.getImageData(0,0,w,h); var d=img.data; var a=self.params.amount; for(var i=0;i<d.length;i+=4){ var r=d[i]; var g=d[i+1]; var b=d[i+2]; var avg=(r+g+b)/3; d[i]=r*(1-a)+avg*a; d[i+1]=g*(1-a)+avg*a; d[i+2]=b*(1-a)+avg*a; } ctx.putImageData(img,0,0); }; });
definePlugin('glow', function(options){ var self=this; self.inputs={source:null}; self.outputs={output:null}; self.params={radius:5,intensity:1}; self.process=function(){ if(!self.inputs.source||!self.outputs.output) return; var ctx=self.outputs.output.getContext('2d'); var w=self.outputs.output.width; var h=self.outputs.output.height; ctx.drawImage(self.inputs.source,0,0,w,h); }; });
definePlugin('kaleido', function(options){ var self=this; self.inputs={source:null}; self.outputs={output:null}; self.params={segments:6}; self.process=function(){ if(!self.inputs.source||!self.outputs.output) return; var ctx=self.outputs.output.getContext('2d'); ctx.drawImage(self.inputs.source,0,0,self.outputs.output.width,self.outputs.output.height); }; });
definePlugin('glint', function(options){ var self=this; self.inputs={source:null}; self.outputs={output:null}; self.params={threshold:0.8}; self.process=function(){ if(!self.inputs.source||!self.outputs.output) return; var ctx=self.outputs.output.getContext('2d'); ctx.drawImage(self.inputs.source,0,0,self.outputs.output.width,self.outputs.output.height); }; });
definePlugin('channelreplace', function(options){ var self=this; self.inputs={source:null}; self.outputs={output:null}; self.params={r:0,g:1,b:2}; self.process=function(){ if(!self.inputs.source||!self.outputs.output) return; var ctx=self.outputs.output.getContext('2d'); ctx.drawImage(self.inputs.source,0,0,self.outputs.output.width,self.outputs.output.height); }; });
definePlugin('bleachbypass2', function(options){ var self=this; self.inputs={source:null}; self.outputs={output:null}; self.params={amount:0.5}; self.process=function(){ if(!self.inputs.source||!self.outputs.output) return; var ctx=self.outputs.output.getContext('2d'); ctx.drawImage(self.inputs.source,0,0,self.outputs.output.width,self.outputs.output.height); }; });
definePlugin('swishpan', function(options){ var self=this; self.inputs={source:null}; self.outputs={output:null}; self.params={speed:1}; self.process=function(){ if(!self.inputs.source||!self.outputs.output) return; var ctx=self.outputs.output.getContext('2d'); ctx.drawImage(self.inputs.source,0,0,self.outputs.output.width,self.outputs.output.height); }; });
definePlugin('shake', function(options){ var self=this; self.inputs={source:null}; self.outputs={output:null}; self.params={amount:5}; self.process=function(){ if(!self.inputs.source||!self.outputs.output) return; var ctx=self.outputs.output.getContext('2d'); var a=self.params.amount; ctx.drawImage(self.inputs.source,a,a,self.outputs.output.width-a*2,self.outputs.output.height-a*2); }; });
definePlugin('flip', function(options){ var self=this; self.inputs={source:null}; self.outputs={output:null}; self.params={horizontal:true}; self.process=function(){ if(!self.inputs.source||!self.outputs.output) return; var ctx=self.outputs.output.getContext('2d'); var w=self.outputs.output.width; var h=self.outputs.output.height; ctx.save(); ctx.scale(self.params.horizontal?-1:1,1); ctx.drawImage(self.inputs.source,self.params.horizontal?-w:0,0,w,h); ctx.restore(); }; });
definePlugin('wave', function(options){ var self=this; self.inputs={source:null}; self.outputs={output:null}; self.params={amplitude:5,frequency:0.02}; self.process=function(){ if(!self.inputs.source||!self.outputs.output) return; var ctx=self.outputs.output.getContext('2d'); ctx.drawImage(self.inputs.source,0,0,self.outputs.output.width,self.outputs.output.height); }; });
})(this);
                                                                                                                                                                      
